/**
 * PROJECT DATA — Bilingual (EN / ZH)
 * -------------------------------------------------------
 * Fields ending in Zh are Chinese versions.
 * Fields marked [TO CONFIRM] are uncertain and must be
 * verified before public launch.
 */

const PROJECTS = [
  {
    id: "extra-vertebra",
    title: "Extra Vertebra",
    titleZh: "附加脊椎",
    year: "[TO CONFIRM]",
    category: "Wearable Robotics / Speculative Design / Physical Computing",
    categoryZh: "可穿戴机器人 / 推测设计 / 实体计算",
    teamType: "[TO CONFIRM — individual or group not specified in source material]",
    teamTypeZh: "[TO CONFIRM — 个人或小组项目待确认]",
    role: "[TO CONFIRM]",
    roleZh: "[TO CONFIRM]",
    placeholderTone: "tone-b",
    oneLiner: "A wearable robotic extension exploring the ambiguous relationship between bodily augmentation, expression and dependence on technology.",
    oneLinerZh: "一个可穿戴机器人延伸装置，探索身体增强、表达与技术依赖之间的模糊关系。",
    context: "A speculative wearable built around the idea of an additional spine, or a 'parasitic organ': a tail-like structure built on a logarithmic spiral skeleton, covered in a fabric skin made using Canadian smocking, and driven by stepper motors that respond to ambient sound.",
    contextZh: "以'附加脊椎'或'寄生器官'为概念设计的推测性可穿戴装置。作品以对数螺旋骨架为结构基础，外覆使用加拿大抽褶工艺制作的布料皮肤，内置步进电机，尾部结构随环境声音的强弱产生不同程度的运动。",
    designQuestion: "What does it mean to wear a body part that is not your own — and where is the line between an augmentation that expresses you and one that you depend on?",
    designQuestionZh: "穿戴一个不属于自己身体的部件意味着什么——能够表达你的增强装置与你所依赖的增强装置，边界在哪里？",
    process: "The spiral structure was modelled in Fusion 360 and built as a physical prototype, paired with a sound sensor, 28BYJ-48 stepper motors and ULN2003 driver boards so that the tail's movement intensity responds to the volume of nearby sound. Canadian smocking was used to give the fabric skin its own texture and stretch behaviour.",
    processZh: "螺旋结构在 Fusion 360 中建模后实体成形，配合声音传感器、28BYJ-48 步进电机和 ULN2003 驱动板，使尾部运动强度对环境音量做出响应。布料外皮采用加拿大抽褶工艺，赋予材料独特的质感与弹性。",
    keyDecisions: "The project deliberately avoids resolving whether the tail is a tool, a companion or a burden — the ambiguity is treated as the point of the piece, rather than something to design away.",
    keyDecisionsZh: "作品刻意保留了尾部究竟是工具、伴侣还是负担的开放性——这种模糊本身是作品的核心，而不是需要解决的问题。",
    outcome: "A functioning wearable prototype whose tail motion responds to ambient sound input, shown as a physical installation / wearable demonstration. [TO CONFIRM — exhibition or presentation context]",
    outcomeZh: "一个可正常运作的可穿戴原型，尾部运动响应环境声音输入，以实体装置／可穿戴演示的形式呈现。[TO CONFIRM — 展览或展示背景待确认]",
    reflection: "This project is where my interest in non-verbal, body-based expression and my product design training met physical computing for the first time, and it directly led into the sound-controlled robotic tail experiments and later technical work.",
    reflectionZh: "这个项目是我对非语言、身体性表达的兴趣与产品设计训练第一次真正相遇的地方，也直接引发了后来的声控机器人尾部实验和更多技术探索。",
    tools: ["Arduino", "28BYJ-48 stepper motors", "ULN2003 driver", "Sound sensor", "Fusion 360", "Canadian smocking"],
  },
  {
    id: "echoes-of-the-heart-sea",
    title: "Echoes of the Heart Sea",
    titleZh: "回音心海",
    year: "[TO CONFIRM]",
    category: "Interactive Installation / Experience Design / EEG Visualisation",
    categoryZh: "互动装置 / 体验设计 / 脑电可视化",
    teamType: "Undergraduate graduation project — [TO CONFIRM individual or group]",
    teamTypeZh: "本科毕业设计 — [TO CONFIRM 个人或小组待确认]",
    role: "[TO CONFIRM]",
    roleZh: "[TO CONFIRM]",
    placeholderTone: "tone-c",
    oneLiner: "An interactive installation translating EEG data into real-time visuals, exploring how a responsive environment may influence emotional experience.",
    oneLinerZh: "一个将脑电数据转化为实时视觉的互动装置，探索响应式艺术环境是否能够影响观者的情绪体验。",
    context: "Designed as my undergraduate graduation project, set in a context of youth emotional wellbeing. The work connects a Muse EEG headset to TouchDesigner, using Alpha, Beta, Theta, Delta and Gamma band data to drive real-time visual changes across a multi-screen space.",
    contextZh: "本科毕业设计项目，背景为青少年情绪体验。作品将 Muse 脑电设备与 TouchDesigner 连接，利用 Alpha、Beta、Theta、Delta 和 Gamma 频段数据，驱动多屏幕空间中的实时视觉变化。",
    designQuestion: "Can a space that visibly responds to a person's own brainwave activity — through light, image and sound — support a felt sense of calm or emotional shift, without presenting itself as a medical or therapeutic device?",
    designQuestionZh: "一个能够可视化呈现观者自身脑电活动的空间——通过光线、图像与声音——能否带来平静或情绪上的某种转变？同时，如何确保它不被误读为医疗或治疗设备？",
    process: "EEG data was streamed via OSC into TouchDesigner, where band values were mapped to colour, movement and screen composition across a multi-screen, lit environment. The installation was tested as an experiential space rather than a controlled clinical study.",
    processZh: "脑电数据通过 OSC 协议传入 TouchDesigner，各频段数值被映射为多屏幕环境中的色彩、动态与画面构成。装置以体验空间的形式进行测试，而非受控的临床实验。",
    keyDecisions: "The project was framed throughout as exploratory and experience-based rather than clinical: it does not claim to treat or diagnose any condition, and the writing around it is kept to 'may influence' rather than measured outcomes.",
    keyDecisionsZh: "整个项目始终以探索性与体验性为框架，而非临床介入：作品不声称能够治疗或诊断任何症状，相关表述保持在'可能影响'而非可量化的结果层面。",
    outcome: "A working multi-screen EEG-responsive installation, exhibited as part of the undergraduate graduation show. [TO CONFIRM — exhibition details / venue]",
    outcomeZh: "一个可正常运作的多屏幕脑电响应装置，作为本科毕业展览作品展出。[TO CONFIRM — 展览详情／场地待确认]",
    reflection: "Working across EEG hardware, OSC data and real-time visuals required treating the technical pipeline as part of the design material itself. It also pushed me to be careful about how speculative wellbeing claims are worded.",
    reflectionZh: "在脑电硬件、OSC 数据传输与实时视觉之间工作，让我意识到技术管线本身就是设计材料的一部分。这也促使我更加审慎地思考如何措辞那些涉及情绪健康的推测性表述。",
    tools: ["Muse EEG headset", "TouchDesigner", "OSC", "Multi-screen display", "Lighting"],
  },
  {
    id: "mossmate",
    title: "Mossmate",
    titleZh: "Mossmate",
    year: "2025",
    category: "Soft Robotics / Interactive Installation / Critical Robotics",
    categoryZh: "软体机器人 / 互动装置 / 批判性机器人学",
    teamType: "Group project — 5 members (Critical Robotics module)",
    teamTypeZh: "小组项目 — 5 人（Critical Robotics 模块）",
    role: "Team leader",
    roleZh: "组长",
    placeholderTone: "tone-a",
    oneLiner: "A soft-robotic sensory installation that responds to a visitor's approach with light, mist and a slow, breath-like motion.",
    oneLinerZh: "一个软体机器人感官装置，当观者靠近时，以光线、雾气和缓慢的呼吸般运动做出回应。",
    context: "Made for the Critical Robotics module with four other students. The group's starting point was a shared observation: existing stress-relief objects, such as tangle toys or squishy balls, tend to release tension through a confrontational gesture — squeezing, popping, snapping. We wanted to try a gentler alternative built around softness in both material and movement, set inside a small forest scene loosely inspired by the character Totoro from Studio Ghibli's My Neighbor Totoro.",
    contextZh: "与四位同学共同完成的 Critical Robotics 模块作品。小组的出发点来自一个共同的观察：现有的减压物品——比如 Tangle 玩具或挤压球——往往通过对抗性的动作来释放压力（挤、压、弹）。我们希望探索一种以柔软为核心的替代方式，在材料和运动上都保持温和，并将其置于一个受宫崎骏电影《龙猫》启发的小型森林场景中。",
    designQuestion: "Can a soft, breath-like interactive object offer a brief sensory pause in a stressful moment, without relying on a confrontational stress-relief gesture?",
    designQuestionZh: "一个柔软的、呼吸般运动的互动物体，能否在压力时刻提供短暂的感官喘息，而不依赖对抗性的减压姿态？",
    process: "We looked at existing sensory-therapy objects — weighted blankets, breathing cushions, fidget toys — to understand the mechanisms behind them, then tested a range of yarns and knitting techniques before settling on hand-crochet for its flexibility and tactile warmth. An early plan to build the internal frame from rigid 3D-printed plastic was dropped once it became clear the rigidity worked against the softness we wanted; we moved to a softer silicone-based 3D-printed frame wrapped in crochet instead. The final piece is a wood-framed box, roughly 40 × 40 × 70 cm, built around two Arduino Uno R4 boards working together — one driving the plant-like lighting, leaf movement and mist, the other driving the character's breathing motion and small narrative details. An HC-SR04 ultrasonic sensor triggers the whole sequence when a visitor comes within about 10 cm.",
    processZh: "我们研究了常见的感官治疗物品——加重毯、呼吸靠垫、手感玩具——理解其背后的机制，再将这些原理转化为更具空间感和叙事性的形式。尝试过多种纱线和编织方式后，最终选择手工钩针：它兼具灵活性与柔软的触感。最初计划使用刚性 3D 打印塑料作为内部骨架，但这与我们希望传达的柔软气质明显冲突，于是改为更软的硅胶基 3D 打印材料配合钩针织物包裹。最终装置是一个约 40×40×70 cm 的木框箱体，内部由两块 Arduino Uno R4 协同控制——一块负责植物类元素的灯光、叶片运动与雾气，另一块负责角色的呼吸动态和叙事细节。HC-SR04 超声波传感器在观者进入约 10 cm 范围内时触发全部交互。",
    keyDecisions: "As team leader I helped set the direction toward 'softness' as the project's organising idea, which is what pushed us to abandon the rigid 3D-printed frame partway through and rebuild it in crochet and soft silicone instead. We also split control across two Arduinos — one for the plant elements, one for the character — so the mechanical and narrative layers could be developed and debugged independently.",
    keyDecisionsZh: "作为组长，我推动了以'柔软'作为项目核心概念的方向，这也是我们中途放弃刚性 3D 打印骨架、改用钩针加软硅胶重新制作的原因。我们还将控制分配给两块 Arduino——一块负责植物元素，一块负责角色——让机械层与叙事层能够独立开发和调试。",
    outcome: "A working prototype: a self-contained box installation where approaching the piece brings up soft lighting, releases a light mist, opens flower-like forms and starts a slow rise-and-fall 'breathing' motion in the central figure.",
    outcomeZh: "一个可正常运作的原型：一个自成体系的箱体装置，观者靠近时会触发柔和灯光、释放轻薄雾气、花朵形态缓缓展开，中心角色开始缓慢的起伏'呼吸'运动。",
    reflection: "We spent more time than planned on material experimentation, which left less time for the software and motion-control work, and the mechanical movement and noise still need further refinement. This is a working prototype rather than a finished object. It draws on published research about nature imagery, soft lighting and deep-pressure stimulation, but we did not run our own studies — so I see it as a speculative, research-informed installation rather than a tested wellbeing tool. [TO CONFIRM — any claims about emotional effect should stay exploratory unless supported by our own testing]",
    reflectionZh: "我们在材料实验阶段花费的时间多于预期，压缩了后期软件和运动控制的开发时间，机械运动的流畅度和噪音控制仍需进一步打磨。这是一个工作原型而非成品。作品参考了关于自然意象、柔和光线和深压刺激的学术研究，但我们没有做过自己的实验——因此我将它定位为一个推测性、研究启发型的装置，而非经过验证的情绪调节工具。[TO CONFIRM — 关于情绪效果的表述，在自行测试支持之前应保持探索性]",
    tools: ["Arduino Uno R4 (×2)", "HC-SR04 ultrasonic sensor", "Stepper & servo motors", "Hand crochet / textile construction", "Silicone-based 3D printing", "Laser cutting"],
  },
  {
    id: "touring-rebuild",
    title: "Touring · Rebuild",
    titleZh: "巡回·再造",
    year: "[TO CONFIRM]",
    category: "Editorial Design / Book Design / Visual System",
    categoryZh: "编辑设计 / 书籍设计 / 视觉系统",
    teamType: "Group project — collective publication",
    teamTypeZh: "集体出版项目",
    role: "Chief editor",
    roleZh: "主编",
    placeholderTone: "tone-d",
    oneLiner: "A large-scale editorial project organising the work of nearly 50 artists into a coherent five-chapter visual and reading system.",
    oneLinerZh: "一个大型编辑设计项目，将近 50 位艺术家的作品整合进一套连贯的五章节视觉与阅读系统。",
    context: "As chief editor, I led the editorial structure of a substantial art archive publication — reported at approximately 600 pages across five chapters, featuring work from close to 50 artists. [TO CONFIRM — exact page count differs between approx. 600 pages and an earlier figure of 300+ pages; must be verified against the printed book]",
    contextZh: "担任主编，负责一本体量庞大的艺术档案出版物——约 600 页，分为五章，收录近 50 位艺术家的作品。[TO CONFIRM — 准确页数在'约 600 页'与早期资料'300+ 页'之间存在差异，须核对成书]",
    designQuestion: "How do you hold a large, uneven body of contributed material — different artists, different formats, different levels of documentation — inside one publication that still reads as a single, coherent object?",
    designQuestionZh: "如何将体量庞大、格式不一的投稿材料——来自不同艺术家、不同媒介、不同文档化程度——整合进一本读来如同单一、连贯整体的出版物？",
    process: "Work included organising submitted material from each artist, establishing an information hierarchy across chapters, building a layout system that could flex across very different types of image and text, and coordinating with collaborators to keep the whole book consistent in pacing and structure.",
    processZh: "工作包括整理每位艺术家提交的材料、建立跨章节的信息层级、构建能够在图像与文字类型之间灵活适配的版式系统，并与协作者协调，保持全书节奏与结构的一致性。",
    keyDecisions: "Rather than designing a single fixed template and forcing every artist's material into it, the system was built around a shared grid and typographic logic that could still flex per chapter — prioritising overall reading rhythm over uniform page-by-page repetition.",
    keyDecisionsZh: "没有设计一套统一的固定模板强制所有材料套用，而是建立了一套以共享网格和字体逻辑为基础、允许按章节灵活调整的系统——优先保证整体阅读节奏，而不是追求每页的机械统一。",
    outcome: "A completed multi-chapter publication documenting the work of close to 50 artists. [TO CONFIRM — final printed page count and distribution status]",
    outcomeZh: "一本完成的多章节出版物，记录近 50 位艺术家的作品。[TO CONFIRM — 最终准确页数与发行状态待确认]",
    reflection: "Editing a publication at this scale is the clearest example in my practice of organising large, messy information into something legible — a skill that now feeds directly into how I think about image experience design and information hierarchy.",
    reflectionZh: "以这种规模编辑一本出版物，是我实践中最清晰地体现'将大量混乱信息组织成可读内容'能力的案例——这种工作方式直接影响了我现在思考图像体验设计和信息层级的方式。",
    tools: ["Editorial design", "InDesign", "Layout systems", "Typography", "Team coordination"],
  },
  {
    id: "visual-graphic-selected",
    title: "Selected Visual & Graphic Work",
    titleZh: "平面与视觉设计作品选",
    year: "[TO CONFIRM]",
    category: "Graphic Design / Visual Identity / Typography Experiments",
    categoryZh: "平面设计 / 视觉识别 / 文字实验",
    teamType: "Mixed — see individual items below",
    teamTypeZh: "混合 — 见各子项目说明",
    role: "See individual items below",
    roleZh: "见各子项目说明",
    placeholderTone: "tone-e",
    oneLiner: "A collection of poster, lettering and identity work, including a graphic-design collaboration and personal typography experiments.",
    oneLinerZh: "一组海报、字体与视觉识别作品，包括一次平面设计协作经历和个人的文字实验。",
    context: "This entry groups several smaller graphic projects: poster and lettering experiments, layout work for my own CV and portfolio, visual exploration connected to the Laiguangying urban identity context [TO CONFIRM — public-sharing status of this project], and participation in a logo design process for Anhui Chery Intelligent Technology Co., Ltd. around August–September 2025 [TO CONFIRM — exact English company name and my specific role on that project].",
    contextZh: "本条目汇集了若干独立的平面项目：海报与字体实验、个人简历和作品集的版式设计、与来广营城市 IP 相关的视觉创作 [TO CONFIRM — 该项目是否可对外公开]，以及参与了安徽奇瑞智能科技有限公司约 2025 年 8—9 月的 Logo 设计过程 [TO CONFIRM — 公司准确英文名称及本人在该项目中的具体角色]。",
    designQuestion: "How do typographic and identity decisions change depending on whether the audience is a brand, a city, or a single reader of a personal document?",
    designQuestionZh: "当受众分别是一个品牌、一座城市或一位个人读者时，字体与视觉识别的决策会发生哪些变化？",
    process: "Each item was developed separately rather than as one campaign. For any project involving a company or a team, this section avoids stating a specific individual role or commercial outcome until it can be confirmed.",
    processZh: "各项目独立开发，而非作为一个整体展开。对于涉及公司或团队的项目，在可以核实之前，本条目不声明具体个人角色或商业落地结果。",
    keyDecisions: "Keeping these as separate, honestly-scoped entries felt more accurate than bundling them into one polished 'identity project' narrative.",
    keyDecisionsZh: "将这些项目作为独立的、如实标注范围的条目分开呈现，比将它们合并成一个经过包装的'视觉识别项目'更符合实际情况。",
    outcome: "A set of individual graphic pieces rather than a single unified project. [TO CONFIRM — which pieces can be shown publicly, especially the Chery logo work and the Laiguangying material]",
    outcomeZh: "一批独立的平面作品，而非单一完整的项目。[TO CONFIRM — 哪些作品可对外展示，尤其是奇瑞 Logo 作品和来广营相关材料]",
    reflection: "Keeping these as separate, honestly-scoped entries felt more accurate than bundling them into one polished 'identity project' narrative.",
    reflectionZh: "将这些项目作为独立的、如实标注范围的条目分开呈现，比将它们合并成一个经过包装的'视觉识别项目'更符合实际情况。",
    tools: ["Adobe Illustrator", "Adobe InDesign", "Adobe Photoshop", "Typography", "Visual identity"],
  },
];

const RESEARCH_PROJECTS = [
  { id: "inspiration-catcher", title: "Inspiration Catcher", year: "[TO CONFIRM]",
    oneLiner: "A concept for capturing fleeting everyday inspiration into a robotic system.",
    oneLinerZh: "一个将日常瞬间灵感捕捉并存入机器人系统的概念。" },
  { id: "lamp-of-echo", title: "Lamp of Echo", year: "[TO CONFIRM]",
    oneLiner: "A sound-visualising lamp concept for deaf and hard-of-hearing users.",
    oneLinerZh: "一个面向听障用户的声音可视化灯具概念。" },
  { id: "cnn-facial-emotion", title: "CNN Facial Emotion Recognition", year: "[TO CONFIRM]",
    oneLiner: "A machine-learning exercise using PyTorch and the FER2013 dataset.",
    oneLinerZh: "使用 PyTorch 和 FER2013 数据集进行的机器学习实验。" },
  { id: "weather-time-recognition", title: "Weather and Time Recognition", year: "[TO CONFIRM]",
    oneLiner: "A two-stage CNN classifying 11 weather categories and 3 time-of-day states.",
    oneLinerZh: "一个识别 11 类天气和 3 类时间状态的两阶段 CNN 系统。" },
  { id: "sound-robotic-tail", title: "Sound-Controlled Robotic Tail", year: "[TO CONFIRM]",
    oneLiner: "An early Arduino experiment — technical groundwork for Extra Vertebra.",
    oneLinerZh: "早期 Arduino 实验，是 Extra Vertebra 的技术前期探索。" },
];

if (typeof module !== "undefined") {
  module.exports = { PROJECTS, RESEARCH_PROJECTS };
}
