/**
 * PROJECT DATA
 * Edit this file to update project content or swap in real images.
 * Replace placeholderTone with: cover: "images/your-photo.jpg"
 */

const PROJECTS = [
  {
  id: "extra-vertebra",
  title: "Extra Vertebra",
  cover: "images/extra-vertebra/1.jpg",
  images: [
    "images/extra-vertebra/2.jpg",
    "images/extra-vertebra/3.jpg",
    "images/extra-vertebra/4.jpg",
    "images/extra-vertebra/5.jpg",
  ],
  video: "images/extra-vertebra/Chroma Spine.mp4",
  year: "2025",
  projectType: "INDIVIDUAL PROJECT",
  category: "Wearable Robotics / Product Design / Physical Computing",
  placeholderTone: "tone-b",
  oneLiner: "A two-stage wearable robotics project that evolved from a sound-controlled tail prototype into a critical investigation of technological body language.",
  context: "Extra Vertebra developed through two connected stages. The first began as a sound-controlled robotic tail prototype exploring whether an artificial body part could support non-verbal emotional expression. Its fishing-line and pulley mechanism established the technical foundation for the later work.\n\nThe second stage expanded this prototype into a research-led wearable project. Rather than treating the tail simply as a controllable tool, the project investigates it as a technological organ situated between bodily augmentation, expression, dependence and intrusion.",
  designQuestion: "How might a simple robotic tail evolve into a technological organ — one that not only extends the body, but also interprets, reveals and potentially shapes the wearer's relationship with their environment?",
  process: "Phase 1 focused on establishing the movement principle. Two servo motors pulled fishing lines through a segmented structure, allowing the tail to sway and bend in response to sound.\n\nPhase 2 retained this line-driven principle while substantially redesigning the system. A logarithmic-spiral structure was developed through Rhino and Grasshopper and produced in flexible TPU. The servo motors were replaced with three stepper motors to provide greater pulling force and stability.\n\nA sound sensor translated ambient noise into changes in movement intensity, while an ultrasonic sensor allowed the tail to retract when another person approached. A heart-rate sensor was also tested as a physiological input, but was replaced because its signal was not sufficiently stable for the final prototype.",
  keyDecisions: "The second stage did not discard the original prototype, but used it as a technical foundation. The line-driven movement principle was retained, while the form, motors, materials and interaction logic were redesigned.\n\nThe project also shifted from asking how an artificial tail could express emotion to questioning what happens when technology begins to interpret the body on the wearer's behalf. This change transformed the work from a functional prototype into a critical investigation of technological body language.",
  outcome: "The project produced two connected outcomes: an initial sound-controlled robotic tail prototype and a more developed wearable installation.\n\nThe final Extra Vertebra prototype combines a flexible TPU body, a logarithmic-spiral structure, three stepper motors and environmental sensors. Its movements respond both to surrounding sound and to the proximity of other people, making external pressure and interpersonal distance visible through an added bodily form.",
  reflection: "The development from the first prototype to Extra Vertebra shifted the project's focus from 'How can a robotic tail move?' to 'What does it mean to live with a technological body part?'\n\nAlthough the tail can amplify environmental conditions and subtle bodily interactions, its movements do not necessarily represent the wearer's true intentions. This ambiguity became central to the project: the device can feel expressive and empowering, but also intrusive, exposing states that the wearer may not have chosen to communicate.",
  tools: [
    "Arduino",
    "Servo Motors",
    "Stepper Motors",
    "Sound Sensor",
    "Ultrasonic Sensor",
    "Rhino",
    "Grasshopper",
    "TPU 3D Printing",
    "Fishing-line Mechanism",
    "Canadian Smocking",
  ],
},
  {
    id: "echoes-of-the-heart-sea",
    title: "Echoes of the Heart Sea",
    cover: "images/echoes/0.jpg",
  images: [
    "images/echoes/1.jpg",
    "images/echoes/2.jpg",
    "images/echoes/3.jpg",
    ],
    video: "images/echoes/TDMovieOut.0.mp4",
    year: "2024",
    projectType: "INDIVIDUAL GRADUATION PROJECT",
    category: "Interactive Installation / Experience Design / Creative Technology",
    placeholderTone: "tone-c",
    oneLiner: "An EEG-responsive interactive installation that translates brainwave activity into real-time visual feedback, creating a space for emotional awareness and reflection.",
    context: "Developed as my undergraduate graduation project, Echoes of the Heart Sea responds to growing concerns around young people's emotional wellbeing and the difficulty of recognising or communicating internal states. The installation connects a Muse EEG headset with TouchDesigner, translating Alpha, Beta, Theta, Delta and Gamma activity into changing colour, movement and composition across a multi-screen environment. Rather than visualising brain data as a clinical chart, the project turns it into an atmospheric and spatial experience.",
    designQuestion: "How might real-time brainwave data be transformed into an accessible visual and spatial experience that helps people notice and reflect on their emotional state?",
    process: "Brainwave data was collected through a Muse EEG headset and transmitted to TouchDesigner via OSC. Five frequency bands — Alpha, Beta, Theta, Delta and Gamma — were used as inputs for the real-time visual system. Different combinations of brainwave activity were mapped to changes in colour, motion, rhythm and screen composition. Instead of assigning a single fixed image to each emotion, I developed a responsive visual language that continuously changed with the incoming data. The system was then expanded from an on-screen experiment into a multi-screen installation, combining real-time visuals, lighting and spatial arrangement to create an immersive viewing environment.",
    keyDecisions: "I chose to translate EEG data into an abstract visual language rather than presenting numerical values or medical-style graphs. This made the data easier to experience while avoiding the suggestion that the installation could accurately diagnose a person's feelings. The visual system was designed to remain fluid rather than assigning one fixed image to one emotion, reflecting the layered and changing nature of emotional states. A multi-screen spatial format was used so that participants encountered the visual feedback as an environment surrounding them, rather than as information displayed on a conventional interface.",
    outcome: "The final outcome was a functioning multi-screen installation in which live EEG signals generated continuous visual changes through TouchDesigner. The project was presented as part of the Central Academy of Fine Arts undergraduate graduation exhibition, demonstrating how personal physiological data could be translated into an experiential visual environment rather than a conventional analytical display.",
    reflection: "This project marked my transition from designing physical products to working with interaction, real-time data and spatial experience. Building the installation required me to treat EEG sensing, OSC transmission and visual mapping as part of the design material rather than as a separate engineering layer. It also made me more aware of the responsibility involved in visualising physiological and emotional data. The project does not claim to measure, diagnose or improve a participant's mental health; instead, it explores how responsive visual environments might encourage attention, interpretation and self-reflection.",
    tools: [
    "Muse EEG",
    "TouchDesigner",
    "OSC",
    "Real-time Data Visualisation",
    "Multi-screen Installation",
    "Spatial Experience Design",
   "Lighting"
  ],
},
  {
    id: "mossmate",
    title: "Mossmate",
    cover: "images/Mossmate/1.jpg",
    images: [
    "images/Mossmate/2.jpg",
    "images/Mossmate/3.jpg",
    "images/Mossmate/4.jpg",
    ],
    video: "images/Mossmate/Mossmate.mp4",
    year: "2025",
    projectType: "TEAM PROJECT · TEAM LEADER",
    category: "Soft Robotics / Interactive Installation / Physical Computing",
    placeholderTone: "tone-a",
    oneLiner: "A soft-robotic sensory installation that responds to a visitor's presence through light, mist and slow, breath-like movement, exploring softness as a form of human–machine interaction.",
    context: "Developed by a five-person team for the Critical Robotics module, Mossmate began with an exploration of softness as both a material quality and an interaction principle. In contrast to stress-relief objects based on squeezing, popping or repetitive force, the project investigates how tactile materials, subtle movement and a forest-inspired atmosphere might create a brief, low-stimulation sensory experience. The installation was loosely inspired by the calm natural environment of My Neighbor Totoro.",
    designQuestion: "How might softness in material, movement and atmosphere shape a gentler form of interaction between people and a robotic object?",
    process: "As team leader, I established the overall concept and coordinated the development of the installation across material experiments, mechanical prototyping, electronics and spatial presentation. We researched sensory objects such as weighted blankets, breathing cushions and tactile toys, then experimented with yarns, crochet techniques, internal structures and different forms of movement. Hand crochet was selected for its flexibility, warmth and ability to form a continuous soft surface. The final installation was constructed inside a wooden frame measuring approximately 40 × 40 × 70 cm. Two Arduino Uno R4 boards divided control between the environmental elements and character animation, while an HC-SR04 ultrasonic sensor activated the sequence when a visitor approached within approximately 10 cm. The response combined RGB lighting, mist, moving leaves, opening flower-like forms and a slow breathing motion.",
    keyDecisions: "As team leader, I guided the project around softness as its central design principle and coordinated how this idea was translated across form, materials, movement and interaction. I completed the crocheted central figure and developed its breathing mechanism, designing and 3D-printing a disc cam that allowed a servo motor to raise the belly through a central rod. A curved internal support was added to produce a softer and more natural movement. I also prototyped the leaf-swing mechanism. An early proposal required two servos for each branch, which would have required twelve servos in total, so I helped simplify the system to two servos controlling all six branches collectively. I also contributed prototypes for the suspended top mechanism and illuminated flower elements, while coordinating the integration of the team's mechanical, electronic and visual components.",
    outcome: "The final outcome was a functioning interactive installation presented as a miniature textile forest. When a visitor approached, the system activated layered lighting, mist, flower movement, swaying leaves and the central figure's slow rise-and-fall breathing motion. The coordinated use of two Arduino controllers allowed the environmental effects and character movements to operate as a single responsive sequence.",
    reflection: "Leading Mossmate showed me how a broad concept such as softness could guide an interdisciplinary project across textiles, mechanical structures, electronics and interaction design. It also required balancing creative direction with practical decisions around time, power, wiring and mechanical complexity. The disc-cam breathing mechanism produced a visible organic motion without requiring a complex gear system, while the simplified leaf mechanism demonstrated the value of reducing technical complexity without losing the intended experience. Because the team devoted substantial time to material experimentation, the software, movement refinement and motor noise would benefit from further development. I therefore present Mossmate as a working, research-informed prototype rather than a finished product or a clinically validated wellbeing tool.",
    tools: [
    "Arduino Uno R4 ×2",
    "HC-SR04 Ultrasonic Sensor",
    "Servo & Stepper Motors",
    "Disc Cam Mechanism",
    "Hand Crochet",
    "3D Printing",
    "Laser Cutting",
    "Interaction Prototyping",
    "Team Leadership"
  ],
},
  {
    id: "eternal-echoes",
    title: "Eternal Echoes",
    cover: "images/eternal-echoes/1.jpg",
  images: [
    "images/eternal-echoes/2.jpg",
    "images/eternal-echoes/3.jpg",
    "images/eternal-echoes/4.jpg",
    "images/eternal-echoes/5.jpg",
  ],
     year: "2024",
    projectType: "INDIVIDUAL SERVICE & PRODUCT DESIGN PROJECT",
    category: "Service Design / UX Research / Digital Product Design",
    placeholderTone: "tone-d",
    oneLiner: "A research-led service and mobile product concept exploring how a digital platform could connect local craftspeople, customers and cultural knowledge within Cao County's coffin-making industry.",
    context: "Cao County has a long-established coffin-making industry supported by local timber resources and craft knowledge, yet many small producers face limited digital visibility, changing customer expectations and the loss of younger workers to larger cities. This project explores how a digital service could connect craftspeople, customers and memorial practices while supporting clearer communication, greater industry visibility and the preservation of local knowledge.",
    designQuestion: "How might a digital service improve communication between local craftspeople and customers while respecting the cultural, emotional and practical sensitivities of the funeral industry?",
    process: "The project began with desk research into funeral customs, local manufacturing and the development of Cao County's coffin industry. I then conducted interviews and exploratory surveys to understand the perspectives of craftspeople, potential customers and people who had moved away from their hometowns. The findings were organised into user needs, stakeholder relationships and service opportunities. I mapped the platform structure, developed separate journeys for customers and craftspeople, created the information architecture and produced low-fidelity wireframes before designing the mobile interface concept.",
    keyDecisions: "I designed the platform around two user identities: customers and craftspeople. Customers could discover makers, explore work, communicate about personalised requirements and access memorial services, while craftspeople could present their skills, manage enquiries and receive orders. I chose a mobile platform because it offered a more accessible way for geographically dispersed users to connect with local producers. The memorial feature was framed as a personal archive rather than a replacement for the deceased, recognising the ethical and emotional risks of AI-generated representations.",
    outcome: "The final outcome was a research-led mobile service concept and interface prototype combining craft discovery, practitioner profiles, direct communication, personalised orders and a digital memorial space. The project demonstrates how service strategy, information architecture and interface design could be brought together within a culturally sensitive industry context.",
    reflection: "This project strengthened my ability to move from broad social and industry research toward a structured digital product concept. It also showed me that a large service system needs a clearer hierarchy of core and secondary functions. In a future iteration, I would narrow the first release to craft discovery, practitioner visibility, communication and order management, then test these functions with a broader group of craftspeople and customers. The digital memorial and AI portrait features would require further research into consent, privacy, ownership and emotional wellbeing before development.",
    tools: [
    "User Research",
    "Stakeholder Mapping",
    "Service System Design",
    "Information Architecture",
    "User Flows",
    "Wireframing",
    "Interface Design",
    "Concept Prototyping"
  ],
},
  {
    id: "visual-communication-archive",
    title: "Visual Communication Archive",
    year: "",
    projectType: "",
    category: "Visual Communication / Identity Design / Typography",
    placeholderTone: "tone-e",
    oneLiner: "A curated selection of identity, poster and typographic work demonstrating visual systems, layout and image-making skills across collaborative and self-initiated projects.",
    context: "This entry brings together several independent graphic and communication projects: poster and lettering experiments, layout work for personal documents, visual exploration connected to urban identity contexts, and participation in collaborative logo and branding processes.",
    designQuestion: "How do typographic and identity decisions change depending on whether the audience is a brand, a city, or a single reader?",
    process: "Each project was developed separately rather than as one campaign, allowing the approach to shift depending on context and audience — from tight editorial systems to more expressive identity work.",
    keyDecisions: "For any project involving a team or external client, the entry is careful not to overstate individual contribution until the full scope can be confirmed.",
    outcome: "A set of individual graphic pieces demonstrating range across identity, typography and editorial layout.",
    reflection: "Keeping these as separate, honestly-scoped entries felt more accurate than bundling them into one polished identity project narrative.",
    tools: ["Adobe Illustrator", "Adobe InDesign", "Adobe Photoshop", "Typography"],
  },
  {
    id: "independent-practice",
    title: "Independent Practice",
    year: "",
    projectType: "",
    category: "Photography / 3D Modelling / Coding",
    placeholderTone: "tone-f",
    oneLiner: "A collection of self-directed visual and technical studies used to develop skills in observation, form-making, digital prototyping and interactive experimentation.",
    context: "Ongoing self-initiated work spanning photography, 3D modelling and coding experiments. These projects sit outside formal briefs and serve as a space for developing visual and technical fluency, testing ideas and building new skills.",
    designQuestion: null,
    process: "Work spans portrait and still-life photography using Canon 5D Mark IV and Sony NEX-5T, 3D modelling and form exploration, and coding experiments including machine-learning exercises using PyTorch and CNN architectures for image classification.",
    keyDecisions: null,
    outcome: "A growing body of personal work organised by medium, used to inform and feed back into practice-based projects.",
    reflection: "Independent practice is where I test composition, light, form and interaction decisions outside of a formal brief — it directly informs how I approach research and visual communication within project work.",
    tools: ["Canon 5D Mark IV", "Sony NEX-5T", "Python", "PyTorch", "Fusion 360", "Studio lighting"],
  },
];

if (typeof module !== 'undefined') { module.exports = { PROJECTS }; }
